- name: Install packages to allow apt to use a repository over HTTPS
  become: true
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present

- name: Add Docker’s official GPG key
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Set up the Docker stable repository
  become: true
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present

- name: Update apt package index after adding Docker repo
  become: true
  apt:
    update_cache: yes

- name: Install Docker Engine
  become: true
  apt:
    name: docker-ce
    state: latest

- name: Install Docker CLI
  become: true
  apt:
    name: docker-ce-cli
    state: latest

- name: Install containerd
  become: true
  apt:
    name: containerd.io
    state: latest

- name: Install compose plugin
  become: true
  apt:
    name: docker-compose-plugin
    state: latest

- name: Ensure Docker is started
  become: true
  service:
    name: docker
    state: started
    enabled: yes

- name: Load image from archive and push to a private registry
  become: true
  community.docker.docker_image:
    name: test
    tag: v1
    load_path: /var/www/html/odin-recipes/ansible/test.tar
    source: load

- name: Install podman
  become: true
  ansible.builtin.apt:
    name: podman
    state: latest

- name: Load image to podman registry
  become: true
  containers.podman.podman_load:
    input: /var/www/html/odin-recipes/ansible/test.tar

- name: Restart a container
  containers.podman.podman_container:
    name: odin-recipe
    image: test:v1
    state: started
    ports:
      - "3000:80"
