---
- name: Deploy Odin Recipe Site
  hosts: all
  pre_tasks:
    - become: true
      ansible.builtin.apt:
        update_cache: yes

  tasks:
    - name: Update Apt Cache
      become: true
      ansible.builtin.apt:
        name: nginx
        state: latest

    - name: Copy nginx conf
      become: true
      ansible.builtin.copy:
        src: ./config-files/nginx.conf
        dest: /etc/nginx/sites-available/odin-recipes.duckdns.org.conf

    - name: Create a symbolic link
      become: true
      ansible.builtin.file:
        src: /etc/nginx/sites-available/odin-recipes.duckdns.org.conf
        dest: /etc/nginx/sites-enabled/odin-recipes.duckdns.org.conf
        state: link

    - name: Creates directory
      become: true
      ansible.builtin.file:
        path: /var/www/html/odin-recipes/
        state: directory

    - name: Copy website files
      become: true
      ansible.builtin.copy:
        src: ../
        dest: /var/www/html/odin-recipes/

    - name: Restart nginx server
      become: true
      ansible.builtin.service:
        name: nginx
        enabled: true
        state: reloaded
