---
- name: Build Docker Image
  hosts: localhost
  tasks:
    - name: build docker
      community.docker.docker_image_build:
        name: test:v1
        path: ../

    - name: Archive image
      community.docker.docker_image:
        name: test
        tag: v1
        archive_path: test.tar
        source: local

- name: Deploy Odin Recipe Site
  hosts: all
  pre_tasks:
    - become: true
      ansible.builtin.apt:
        update_cache: yes

  tasks:
    - name: Install nginx
      become: true
      ansible.builtin.apt:
        name: nginx
        state: latest

    - name: Copy nginx conf
      become: true
      ansible.builtin.copy:
        src: ./config-files/nginx.conf
        dest: /etc/nginx/sites-available/odin-recipes.duckdns.org.conf

    - name: Create a symbolic link
      become: true
      ansible.builtin.file:
        src: /etc/nginx/sites-available/odin-recipes.duckdns.org.conf
        dest: /etc/nginx/sites-enabled/odin-recipes.duckdns.org.conf
        state: link

    - name: Creates directory
      become: true
      ansible.builtin.file:
        path: /var/www/html/odin-recipes/
        state: directory

    - name: Synchronize website files
      become: true
      ansible.posix.synchronize:
        src: ../../
        dest: /var/www/html/odin-recipes
        rsync_opts:
          - "--exclude=.git"

    - name: Restart nginx server
      become: true
      ansible.builtin.service:
        name: nginx
        enabled: true
        state: reloaded

    - name: Load Docker
      ansible.builtin.include_tasks: ./tasks/docker.yaml

    - name: Delete ansible folder
      become: true
      ansible.builtin.file:
        state: absent
        path: /var/www/html/odin-recipes/ansible
