---
- name: Deploy Odin Recipe Site
  hosts: all
  pre_tasks:
    - become: true
      ansible.builtin.apt:
        update_cache: yes

  tasks:
    - name: Update Apt Cache
      become: true
      ansible.builtin.apt:
        name: nginx
        state: latest
