name: Deploy Odin Recipe
run-name: ${{ github.actor }}

on: workflow_dispatch

jobs:
  Deploy-Odin-Recipe:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install Ansible
        run: sudo apt-get install -y ansible python3-docker

      - name: Load the Key
        run: |
          cd ansible
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > Adaeri_AWS_EC2.pem
          chmod 400 Adaeri_AWS_EC2.pem

      - name: Connect to twingate
        uses: twingate/github-action@v1
        with:
          service-key: "${{ secrets.TWINGATE_KEY }}"

      - name: Deploy
        run: |
          cd ansible
          twingate resources
          docker ps
          ansible-playbook -i inventry.yaml init.yaml
